### ISSUE TITLE
Reg. Software Workflow

### ISSUE THREAD

**Issue by CaptainMack** [peopleplusrobots/robo-op#1]
Hi!

I love the idea behind the project, but I've noticed that there's not really any information in: https://github.com/peopleplusrobots/robo-op/wiki/3.-Software:-Workflow-&-Integration

I am also guilty of having too many things on my table, so I won't stress about it - I simply need a few details for getting the Arduino->Processing->Robot communication software to work.

//Chris

**Comment by zackjw** [comment]
Hi Chris,

Thank you for getting in touch.  I'm copying Madeline and Mike here as they've been refining that workflow since October.  I'm no longer in the same lab as them and, regardless, I had less to do with the software pipeline and more to do with design and fabrication of the object itself.

Hopefully they can get you what you need.  Should be, roughly, an Arduino/Xbee > Java > Grasshopper(Rhino3D)> ABB Controller/IP address flow.

Please keep in contact.  We're thrilled to hear that someone's appropriating the project!

Best,
Zack

**Comment by madelinegannon** [comment]
Hi Chris,

Thanks for your patience ... I've uploaded a new _Getting Started Tutorial_ [here](https://github.com/peopleplusrobots/robo-op/wiki/3.-Software:-Getting-Started-Tutorial) and some more advanced (but messy!) example projects [here](https://github.com/peopleplusrobots/robo-op/wiki/4.-Example-Projects).

Let us know how it goes!

-Madeline
